server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueadmin?serverTimezone=UTC
    username: root
    password: '000000'
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml